name: Deploy app

on:
  push:

push:
  branches:    # Array of patterns that match refs/heads
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: npm install, build, and test
      run: |
        yarn install
        yarn deploy
