name: Node CI

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    artifacts:
      expire_in: 1 hour 30 minutes
      paths: build
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        yarn install
        yarn run build --if-present  
        
  deploy:  
    runs-on: ubuntu-latest    
    needs: build
    when: manua
    steps:    
    - name: Deploy to GitHub pages
      run: |
        yarn deploy
      allow_failure: false

