name: Node CI

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn install
        yarn run build --if-present  
        
  deploy:  
    runs-on: ubuntu-latest   
    
    needs: build
    when: manual
    steps:    
    - name: Deploy to GitHub pages
      run: |
        yarn deploy
      allow_failure: false

