name: Install and Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    needs: install
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: yarn install & build
      run: |
        yarn install
        yarn build

  test:
    runs-on: ubuntu-latest

    needs: install
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - name: yarn install & test
        run: |
          yarn install
          yarn test
